server:
  # Pterodactyl injeta SERVER_PORT. Se não houver, usa 8080.
  port: ${SERVER_PORT:8080}
  # Necessário para entender que está atrás de um proxy (se usar https://gepard.jaooo.tk)
  forward-headers-strategy: framework

spring:
  application:
    name: gepard

  threads:
    virtual:
      enabled: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - https://www.googleapis.com/auth/calendar
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-authentication-method: client_secret_basic
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent

# --- CONFIGURAÇÃO CUSTOMIZADA ---
gepard:
  # Define a URL pública. No Pterodactyl, definiremos isso na variável APP_BASE_URL
  base-url: ${APP_BASE_URL:http://localhost:${server.port}}

  telegram:
    bot-username: ${TELEGRAM_BOT_USERNAME}
    bot-token: ${TELEGRAM_BOT_TOKEN}

---
# --- AMBIENTE DE DESENVOLVIMENTO (H2) ---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:file:./data/gepard_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

---
# --- AMBIENTE PTERODACTYL (MariaDB) ---
spring:
  config:
    activate:
      on-profile: ptero

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

---
# --- AMBIENTE DE PRODUÇÃO (ORACLE OCI) ---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=${ORACLE_HOST}))(connect_data=(service_name=${ORACLE_SERVICE_NAME}))(security=(ssl_server_cert_dn=${ORACLE_CERT_DN})))
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate